### ISSUE TITLE
bro just doing advertisement here

### ISSUE THREAD

**Issue by kaileysong** [AIFSH/FancyVideo-ComfyUI#3]

**Comment by TurningTide** [comment]
Yeah, this explains a lot of the issues and the lack of updates.
For example, using diffusers==0.11.1 breaks lots of custom nodes.
And the resulting video is just a transition from the first frame to a complete blur.

**Comment by kaileysong** [comment]
> Yeah, this explains a lot of the issues and the lack of updates. For example, using diffusers==0.11.1 breaks lots of custom nodes. And the resulting video is just a transition from the first frame to a complete blur.

Seriously I can't even get Comfy import it correctly. Next I'll go straight 360CVGroup's FancyVideo

**Comment by zzddwyff** [comment]
gzip.BadGzipFile: Not a gzipped file (b've')???/？？？？？
